### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by aidenZou** [aidenZou/mock-data#1]
## 规划中

- [ ] 支持 https
- [ ] 添加按项目组来维护 mock 数据功能
- [ ] 添加公开、只读、私密权限 （二期权限）

## 已支持

- [x] GET、POST请求
- [x] cors 跨域
- [x] mockjs 模拟数据
- [x] 同一接口支持 2种场景返回 mock 数据（如：成功、失败）
- [x] json 语法检查
- [x] 添加用户功能
- [x] 添加公开、只读、私密权限 （一期权限完成）
- [x] 支持线程挂起指定秒数再响应
- [x] 支持 jsonp 跨域

### sleep

现已支持模拟接口休眠指定秒数
用法：URL添加参数(限制最大8秒)；
举例：URI?_sleep=3 该请求休眠3秒后返回结果
http://mock.51coding.wang/api/test/user?_sleep=3

### jsonp
用法：URI?_callback=callbackFunctionName 或 URI?callback=callbackFunctionName
默认：[ '_callback', 'callback' ]；
举例：
http://mock.51coding.wang/api/test/user?_callback=callbackFunctionName
http://mock.51coding.wang/api/test/user?callback=callbackFunctionName

### 举几个🌰
**jsonp请求 并 延迟 3秒后返回**
http://mock.51coding.wang/api/test/user?_sleep=3&_callback=callback
